### ISSUE TITLE
Impossible to set ingress pod's resources (requests/limits for cpu/memory)

### ISSUE THREAD

**Issue by OdyX** [akyriako/typesense-operator#116]
In the cluster I'm deploying this to, `resources.limits.memory` is enforced to be equal to `resources.requests.memory`. I can set pod requests/limits for the typesense & metrics pods as follows:

```yaml
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  name: ts-test-0
spec:
  image: typesense/typesense:28.0
  # (…)
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      memory: 256Mi
  metrics:
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        memory: 64Mi
```

But there's no way to set this for the ingress pod.
