### ISSUE TITLE
typesense cluster went unready randomly

### ISSUE THREAD

**Issue by knownasmobin** [akyriako/typesense-operator#122]
I recently set up my Typesense cluster with the following configuration:

```yaml
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  name: uranus-typesense-prod
  namespace: uranus-typesense-prod
spec:
  # Required: The Typesense image to use
  image: typesense/typesense:28.0
  
  # Number of replicas in the cluster (1, 3, 5, or 7)
  replicas: 5
  
  # API port configuration (default: 8108)
  apiPort: 8108
  
  # Peering port configuration (default: 8107)
  peeringPort: 8107
  
  # Enable CORS (default: false)
  enableCors: true
  
  corsDomains: <DOMAINS>
  
  # Required: Storage configuration
  storage:
    size: 1Gi
    storageClassName: <STORAGE CLASS>
  
  # Resource requirements
  resources:
    requests:
      cpu: 700m
      memory: 1.5Gi
    limits:
      cpu: 1
      memory: 3Gi
  
  # Admin API key reference (points to a secret)
  adminApiKey:
    name: typesense-admin-api-key
  
  # Optional: Ingress configuration for external access
  ingress:
    host: search.arzdigital.com
    ingressClassName: traefik
    clusterIssuer: letsencrypt-prod
  
  # Optional: Metrics configuration
  metrics:
    image: akyriako78/typesense-prometheus-exporter:0.1.7
    release: prometheus
    interval: 15
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  resetPeersOnError: true
  incrementalQuorumRecovery: true
``` 

However, I’ve encountered an issue: sometimes the cluster status randomly changes to “Unready.” Four of the StatefulSets are removed, and one remains with QuorumReady = false, but it never attempts to recover the cluster. I’m not sure what caused those StatefulSets to be removed, and despite this being a critical problem, I haven’t found any reason why the cluster doesn’t initiate recovery.

[manager.txt](https://github.com/user-attachments/files/20141271/manager.txt)

[typesense.txt](https://github.com/user-attachments/files/20141272/typesense.txt)

helm chart version is 0.2.22
