### ISSUE TITLE
Ingress pods can't run on readOnlyRootFilesystem

### ISSUE THREAD

**Issue by OdyX** [akyriako/typesense-operator#128]
(Thanks for your fixing of #116 )

The ingress pods can't be configured to work on `readOnlyRootFilesystem`.

Via Kyverno, I can make them work with

```
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                containers:
                  - (image): "nginx:*"
                    volumeMounts:
                      - name: nginx-var-cache
                        mountPath: /var/cache/nginx
                      - name: run
                        mountPath: /run
                volumes:
                  - name: nginx-var-cache
                    emptyDir: {}
                  - name: run
                    emptyDir: {}
```

So I'd say either:
* the used image should work on  `readOnlyRootFilesystem`
* the image should be configurable
* the volumes should be configurable
* default emptyDir volumes should be set
