### ISSUE TITLE
Ingress returning 404 when sending requests to /multi_search

### ISSUE THREAD

**Issue by reginbald** [akyriako/typesense-operator#137]
Is it possible to change the ingress rule from */* to */\**. 

I'm having issues where the aws load balancer is returning 404 for requests sent to the /multi_search endpoint.

https://github.com/akyriako/typesense-operator/blob/d94d0b22b5408520a002902935ddfd6cbe50a62c/internal/controller/typesensecluster_ingress.go#L303

My setup running in AWS EKS

```
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
  name: typesense-cluster
spec:
  image: typesense/typesense:27.1
  replicas: 3
  storage:
    size: 100Mi
    storageClassName: auto-ebs-sc
  adminApiKey:
    name: typesense
  enableCors: true
  corsDomains: {{ .Values.corsDomains | join "," }}
  ingress:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: {{ .Values.url }}
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: instance
        alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificate_arn }}
        alb.ingress.kubernetes.io/healthcheck-path: /health
      host: {{ .Values.url }}
      clusterIssuer: letsencrypt
      ingressClassName: alb
```
