### ISSUE TITLE
Setting TYPESENSE_ENABLE_CORS directly, not just by setting TYPESENSE_CORS_DOMAINS

### ISSUE THREAD

**Issue by rilyw** [akyriako/typesense-operator#18]
Now that typesense is deployed in our cluster, we wanted to interact with it for debugging purposes through the typesense dashboard: [https://bfritscher.github.io/typesense-dashboard](https://bfritscher.github.io/typesense-dashboard). Instead of using the dashboard hosted on github.io we would like to run the docker image locally. The problem with that is, that the value _localhost_ is not a valid domain. Typesense seems to use _*_ as a wildcard for the domains if non are explicitly set, but it seems impossible to set this in typesense, as even with the docker image it does not allow any domains.

> corsDomains: "*"

A workaround for us was to delete the value inside the statefulset.
From this:
``` yaml
        - name: TYPESENSE_ENABLE_CORS
          value: "true"
        - name: TYPESENSE_CORS_DOMAINS
          value: *
        - name: TYPESENSE_RESET_PEERS_ON_ERROR
```

To this:
```yaml
        - name: TYPESENSE_ENABLE_CORS
          value: "true"
        - name: TYPESENSE_CORS_DOMAINS
        - name: TYPESENSE_RESET_PEERS_ON_ERROR
```

When we deleted the whole variable, it was seemingly one step too far and did not set any domains in typesense.

We would like to be able to enable and set these values from their configuration instead of in the cluster after deploying. It is just for debugging/testing purposes in our case, but it would still be a useful feature.

Thanks in advance :3
