### ISSUE TITLE
Add overwrite in statefulset for peering address

### ISSUE THREAD

**Issue by rilyw** [akyriako/typesense-operator#2]
While deploying Typesense on our cluster we encountered a problem described in this issue on the Typesense github repository.
> https://github.com/typesense/typesense/issues/465

The fix in this [comment](https://github.com/typesense/typesense/issues/465#issuecomment-1727704144) eliminates the problem, but we can not add it to the configuration of the custom resource, since the crd and statefulset don't allow any argument to change the peering address. 
The only working solution at the moment is to install the helm chart and then add this:
``` yaml
- name: TYPESENSE_PEERING_ADDRESS
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.podIP
```
to the running statefulset. For the deployment we would like to just install the helm chart and not make any changes to the running system.

A solution could look something like this:

Add a variable named "TYPESENSE_PEERING_ADDRESS" to the Env property of the statefulset [here](https://github.com/akyriako/typesense-operator/blob/57e20b81ce45aa595a10d6c3d03e72933381f034/internal/controller/typesensecluster_statefulset.go#L92).

**Comment by akyriako** [comment]
Hi @rilyw, this operator has been developed to explicitly solve the exact problem described in this issue https://github.com/typesense/typesense/issues/465, and it does; check [Problem 1](https://github.com/akyriako/typesense-operator?tab=readme-ov-file#problem-1-quorum-reconfiguration) & [Problem 2](https://github.com/akyriako/typesense-operator?tab=readme-ov-file#problem-2-recovering-a-cluster-that-has-lost-quorum) analysis in the README.md. By just changing the peering port **will not** solve you the problems arousing when pods leave or join the cluster!

Nevertheless the operator is still in beta phase; heavily tested and gathering feedback (thank you very much both for the interest and opening this issue). Graduating to a production-ready state is expected by end of January. As a matter of fact, lots of staff must be added in the (re)configuration of the `TypesenseCluster` CRD (like tolerations, node selector and as you mentioned custom API and Peering ports among others).

Your requested changes are valid and will be incorporated soon, latest till end of next week you will be able to test them.

Cheers!

**Comment by akyriako** [comment]
Hi @rilyw, I think I jumped **too** fast answering you back (maybe it's still early in my TZ and I urgently need more coffee I guess). The user-defined API and Peering ports **are already implemented and tested**. Check the specs of the `TypesenseCluster` CRD [here](https://github.com/akyriako/typesense-operator/blob/57e20b81ce45aa595a10d6c3d03e72933381f034/api/v1alpha1/typesensecluster_types.go#L38). The explanation about https://github.com/typesense/typesense/issues/465 stays as it is. What you need to do, in order to provision a cluster with user-defined ports, is to **change** the manifest you used to install a `TypesenseCluster` CR by adding an `apiPort` and a `peeringPort` (they default to `8108` & `8107` respectively and if you don't provide an explicit value they are just omitted from the yaml manifest by design):

```yaml
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: cluster-1
spec:
  image: typesense/typesense:27.1
  apiPort: 28108
  peeringPort: 28107
  replicas: 3
  storage:
    size: 10Mi
    storageClassName: csi-disk
```

The values `28108` & `28107` are just for the sake of the example, defined whatever fits your scenario.
