### ISSUE TITLE
Purge hot loop when Typesense is lagging

### ISSUE THREAD

**Issue by akyriako** [akyriako/typesense-operator#23]
for example when ts gets into this state: `[raft_server.cpp:797] 1197 queued writes > healthy write lag of 500`, the reconciler forces a purge and ts remains in lagging state.

**Comment by fibis** [comment]
This would be nice! We have a reality big dataset that needs some minutes to load into the memory. Before this is done, the operator is already killing the node.

**Comment by akyriako** [comment]
Hi @fibis, very important issue; it's on the top of my work stash at the moment

**Comment by mleklund** [comment]
Can I ask if your `--healthy-read-lag` == `--healthy-write-lag` ?  Or maybe you are using the defaults and your `--healthy-read-lag` is 1000 in this case.  [It looks like](https://threads.typesense.org/2J2c6a2) if your lag is above `--healthy-write-lag` there should be no issue, but writes will start to give 503.  However if your writes lag more then `--healthy-read-lag`, the node is considered unhealthy.  It seems there could be 2 issues at play:

1) if you routinely are running big imports, size your `--healthy-read-lag` appropriately.  This is an operational issue.
2) An initializing node should not be considered initially healthy until after it is healthy at least once.  A startupProbe could smooth this over.  It could have an arbitrarily high default failureThreshold that is configurable:

```
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /health
            port: 8108
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```

would give 10 minutes to startup, checking every 10 seconds.  

As for operator handling, maybe it needs to check `containersReadyCondition` before making a health check?  And should the operator be [checking debug](https://typesense.org/docs/guide/high-availability.html#verifying-cluster-formation) to determine quorum, and not be relying on node health?  It seems the node can be unhealthy, i.e. read lagging, but not have lost quorum. And if not killed, it might recover, in the mean time if marked unhealthy, the service would quit sending traffic to it until it recovers (or is killed off by k8s).
