### ISSUE TITLE
[Bug] Additional server configuration does not set environment variables

### ISSUE THREAD

**Issue by rilyw** [akyriako/typesense-operator#26]
The new feature from #22 does not work for us. We create a ConfigMap and use the name of it in _additionalServerConfiguration_ as described in the sample, but the defined variables are not set for the deployed pods.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ts-server-config
data:
  TYPESENSE_ENABLE_SEARCH_ANALYTICS: "true"
  TYPESENSE_ENABLE_CORS: "true"
  TYPESENSE_ANALYTICS_DIR: "/data/analytics-data"
  TYPESENSE_ANALYTICS_FLUSH_INTERVAL: "60"
---
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: {{ include "typesense-server.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  image: "{{ .Values.image.repository}}:{{ .Values.image.tag}}"
  replicas: {{ .Values.replicas }}
  storage:
    size: {{ .Values.persistence.size }}
    storageClassName: {{ .Values.persistence.storageClassName }}
  additionalServerConfiguration:
    name: ts-server-config
```
I cannot see anything wrong with our configuration, it is basically the same as in the samples.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: c-kind-2-config
data:
  TYPESENSE_ENABLE_SEARCH_ANALYTICS: "true"
  TYPESENSE_ENABLE_CORS: "true"
---
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: c-kind-2
spec:
  image: typesense/typesense:26.0
  replicas: 1
  additionalServerConfiguration:
    name: c-kind-2-config
.
.
.
```
I also tried adding the ConfigMap to the same namespace or deploying it in default, but to no avail. _TYPESENSE_ENABLE_CORS_ stays false and the other defined variables are not set at all in the pods/statefulset.

```
Environment:
      TYPESENSE_API_KEY:               <set to the key 'typesense-api-key' in secret 'typesense-common-bootstrap-key'>  Optional: false
      TYPESENSE_NODES:                 /usr/share/typesense/nodes
      TYPESENSE_DATA_DIR:              /usr/share/typesense/data
      TYPESENSE_API_PORT:              8108
      TYPESENSE_PEERING_PORT:          8107
      TYPESENSE_PEERING_ADDRESS:        (v1:status.podIP)
      TYPESENSE_ENABLE_CORS:           false
      TYPESENSE_CORS_DOMAINS:          
      TYPESENSE_RESET_PEERS_ON_ERROR:  true
Mounts:
      /usr/share/typesense from nodeslist (rw)
      /usr/share/typesense/data from data (rw)
```

We use the the version 0.2.7 of the operator.

```
Containers:
  manager:
    Container ID:  containerd://2d6085364c62744e5b9fffd5d3e63b5f1ed5ee499279ab121b15b2049a9b7cc0
    Image:         akyriako78/typesense-operator:0.2.7
    Image ID:      docker.io/akyriako78/typesense-operator@sha256:02dc69839be9b5ba873ff18c200a8e41e136aff4642d2efdc822f4622d082965
```

Is there something wrong with how we do it or should it work like that?
