### ISSUE TITLE
[Bug] Setting bootstrap key on startup not working

### ISSUE THREAD

**Issue by rilyw** [akyriako/typesense-operator#27]
We would like to be able to set the bootstrap key, as it removes the step of decoding the generated key and adding it to some keystore/vault. It would be easier to set some key in a vault and start typesense with that key. But we cannot get the changes from #13 working. 

``` yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: typesense-common-bootstrap-key
  namespace: typesense
type: Opaque
data:
 typesense-api-key: eHl6Cg==
```

Naturally the key is just a placeholder and is just used for debugging, as the key is "xyz".

``` yaml
spec:
  adminApiKey:
    name: typesense-common-bootstrap-key
```

The sample is the same with a different key value.

``` yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: typesense-common-bootstrap-key
type: Opaque
data:
  typesense-api-key: SXdpVG9CcnFYTHZYeTJNMG1TS1hPaGt0dlFUY3VWUloxc1M5REtsRUNtMFFwQU93R1hoanVIVWJLQnE2ejdlSQ==
---
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: c-otc-1
spec:
  adminApiKey:
    name: typesense-common-bootstrap-key
.
.
.
```

We would assume this set the bootstrap key to our defined value, but when sending requests we are unauthorized with our key. The problem is that there is only one secret and that has our value, so we cannot get the actual value of the bootstrap key for our pods. We somehow overwrote the secret that was used.

```
$ kubectl get secret -n typesense 
NAME                             TYPE     DATA   AGE
typesense-common-bootstrap-key   Opaque   1      6m7s
```

I then changed the name of our secret from _typesense-common-bootstrap-key_ to _typesense-bootstrap-key_ and it was still the only secret, but now the containers could not start as they did not find _typesense-common-bootstrap-key_ secret, even though the name value for the key was _typesense-bootstrap-key_.

``` yaml
spec:
  adminApiKey:
    name: typesense-bootstrap-key
```

```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  41s               default-scheduler  Successfully assigned typesense/ts-server-sts-1 to cluster-...
  Normal   Pulled     9s (x4 over 26s)  kubelet            Container image "typesense/typesense:27.1" already present on machine
  Warning  Failed     9s (x4 over 26s)  kubelet            Error: secret "typesense-common-bootstrap-key" not found
```

Is there anything wrong with our configuration?

**Comment by akyriako** [comment]
the bootstrap key is bootstraping the cluster once in the beginning and for all - no way back or replacements, you cannot replace it at will (unless if you create another key via typesense itself, encode it to base64 and then replace it in the Secret - but i guess that might be an "emergency" situation and has nothing to do with the operator) which sounds like your case:

> We somehow overwrote the secret that was used.

**Comment by rilyw** [comment]
The secret is in our helm chart in the same file as the TypesenseCluster. It gets deployed at the same time. We are not trying to change the bootstrapping key after the pods already are deployed. 

> We somehow overwrote the secret that was used.

The situation I meant with this is as follows:

1. The TypesenseCluster gets deployed.
  1.1. The secret gets deployed at the same time.
2. The operator apperently still generates an api key
  2.1 The TYPESENSE_API_KEY variable in the pod has some generated value and not our value
3. There is only one secret and it has our defined value

I changed the name of the key to see if the problem layed in the check of the operator that looks at the TypesenseCluster and if the _spec.adminApiKey_ variable is set or not. If after the name change there were 2 secrets I would know that the operator has not processed the given api key and instead created a new one that was then used by the typesense pods. But if there is only 1 secret after the name change, that would mean there is nothing wrong with the processing but something else.

I did not rename the secret in kubernetes, but in our helm chart and then I used
``` bash
helm upgrade ts-server path/to/chart
```

The pods were not restarted after the upgrade so I deleted them. The operator started them up, but they were still looking for a secret named _typesense-common-bootstrap-key_ which now did not exist. This just means that the operator did not create a secret as we defined one ourselfs. 


Onto the next step of the problem.


I uninstalled our helm chart and reinstalled it, now the pods should not look for _typesense-common-bootstrap-key_ as the secret, but _typesense-bootstrap-key_. That is the case, yet the TYPESENSE_API_KEY variable in the pod is not the decoded value of the secret, but some other generated value. Naturally sending requests with our defined key will not work in this situation.

After updating the crd, as it was the fix for problem #26, the situation is different but the problem still the same. Now the correct value is in the pod, but any request is still unauthorized.

``` bash
$ env | grep TYPESENSE_
TYPESENSE_API_KEY=xyz
```

``` bash
$ curl 'http://localhost:8108/keys' \
    -X GET \
    -H "X-TYPESENSE-API-KEY: xyz"
{"message": "Forbidden - a valid `x-typesense-api-key` header must be sent."}
```

Now I do not know where the differing bootstrap key is coming from or how the pod has a bootstrap key that is different from the TYPESENSE_API_KEY variable.

**Comment by akyriako** [comment]
Ok I found the bug; your deduction is somehow (under conditions) correct => The Secret was deployed **after** the Helm Chart (I don't imply you should follow a deployment order; the contrary) and the Operator **falsely** creates in this case a new Secret with the exact very name you provided in `spec.adminApiKey`! Definitely this shouldn't happen but it should "fail/wait" till the external Secret is present in the cluster. I will fix it, thanks for digging the bug.

**Comment by rilyw** [comment]
I am sorry, but for me this bug was not fixed by #28. When I set my own key as _adminApiKey_, no other secret is created by the operator. When looking inside the pods, I can see my value is set as _TYPESENSE_API_KEY_, but I still cannot send requests to my typesense. I am unauthorized when using my key.

> unless if you create another admin key via typesense itself, encode it to base64 and then replace it in the Secret , then recreate the StatefulSet Pods to take the new value in their envvars

I even tried this as "emergency", but even with my newly set key in the statefulset I was unauthorized for requests.

The only way to get a working bootstrap key is to not set _adminApiKey_ and let the operator create a secret.

``` bash
$ env | grep TYPE
TYPESENSE_API_KEY=X3ggfOrvn1dfTV1L
```
``` bash
$ curl 'http://localhost:8108/keys' \
    -X GET \
    -H "X-TYPESENSE-API-KEY: X3ggfOrvn1dfTV1L"
{"message": "Forbidden - a valid `x-typesense-api-key` header must be sent."}
```

**Comment by akyriako** [comment]
**Steps to reproduce:**

1. Create a temporary brand new **kind** cluster: `kind create cluster --name bug-27`
2. Create an dummy Admin Api Key and encode it to base64: (plain) P@ssw0rd => (base64)  UEBzc3cwcmQ=
3. Deploy the operator:

```
helm repo add typesense-operator https://akyriako.github.io/typesense-operator/
helm repo update

helm upgrade --install typesense-operator typesense-operator/typesense-operator -n typesense-system --create-namespace
```

4. Deploy the samples (`StorageClass`, `Secret`, `TypesenseCluster`):

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: typesense-local-path
provisioner: rancher.io/local-path
reclaimPolicy: Delete
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Secret
metadata:
  name: typesense-common-bootstrap-key
type: Opaque
data:
  typesense-api-key: UEBzc3cwcmQ=
---
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  name: c-kind-1
spec:
  image: typesense/typesense:27.1
  replicas: 3
  storage:
    size: 10Mi
    storageClassName: typesense-local-path
  adminApiKey:
    name: typesense-common-bootstrap-key
  ingress:
    referer: referer.example.com
    host: host.example.com
    ingressClassName: nginx
    clusterIssuer: lets-encrypt-prod
  scrapers:
    - name: docusaurus-io
      image: typesense/docsearch-scraper:0.11.0
      config: "{\"index_name\":\"docusaurus-io\",\"start_urls\":[\"https://docusaurus.io/\"],\"sitemap_urls\":[\"https://docusaurus.io/sitemap.xml\"],\"sitemap_alternate_links\":true,\"stop_urls\":[\"/tests\"],\"selectors\":{\"lvl0\":{\"selector\":\"(//ul[contains(@class,'menu__list')]//a[contains(@class, 'menu__link menu__link--sublist menu__link--active')]/text() | //nav[contains(@class, 'navbar')]//a[contains(@class, 'navbar__link--active')]/text())[last()]\",\"type\":\"xpath\",\"global\":true,\"default_value\":\"Documentation\"},\"lvl1\":\"header h1\",\"lvl2\":\"article h2\",\"lvl3\":\"article h3\",\"lvl4\":\"article h4\",\"lvl5\":\"article h5, article td:first-child\",\"lvl6\":\"article h6\",\"text\":\"article p, article li, article td:last-child\"},\"strip_chars\":\" .,;:#\",\"custom_settings\":{\"separatorsToIndex\":\"_\",\"attributesForFaceting\":[\"language\",\"version\",\"type\",\"docusaurus_tag\"],\"attributesToRetrieve\":[\"hierarchy\",\"content\",\"anchor\",\"url\",\"url_without_anchor\",\"type\"]},\"conversation_id\":[\"833762294\"],\"nb_hits\":46250}"
      schedule: '*/2 * * * *'

```

5. Wait till the controller finishes with its reconciliation staff and declares `TypesenseCluster` c-kind-1 as _Ready_
6. Create a debugging pod on a terminal: `kubectl run tmp-shell -i --tty --image nicolaka/netshoot` 
7. Perform in-cluster check: `curl -w "\n" http://c-kind-1-svc:8108/keys -X GET -H "X-TYPESENSE-API-KEY: P@ssw0rd"` (**Result**: `{"keys": []}`) :heavy_check_mark: 
8. Exit the debug pod terminal session.
9. Port-forward c-kind-1-svc and perform out-of-cluster check: `curl -w "\n" http://localhost:8108/keys -X GET -H "X-TYPESENSE-API-KEY: P@ssw0rd"` (**Result**: `{"keys": []}`) :heavy_check_mark: 
10. Perform scraper check: Check the log files of the docusaurus-io-scraper-XXXXXXX-YYYYY pods to see if scraper was able to use the provider api key to write in typesense the tokens that has scraped. (**Result**: affirmative, it takes long time to finish though; don't wait for it). :heavy_check_mark: 

Try the steps above and let me know. I didn't see any of the behavior you mention.
