### ISSUE TITLE
Ingress in not updated when ingressClassName is updated

### ISSUE THREAD

**Issue by jmiller-ca** [akyriako/typesense-operator#37]
I had the following manifest running, and updated the `ingressClassName: typsense-external` and confirmed the change in the cluster. After 10 minutes I choose to delete the ingress from the deployment and it was recreated correctly with the new ingress class.

```
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/part-of: typesense
  name: c01
  namespace: poc01-typesense
spec:
  additionalServerConfiguration:
    name: typesense-config
  adminApiKey:
    name: typesense-bootstrap-key
  enableCors: false
  image: typesense/typesense:27.1
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    clusterIssuer: letsencrypt
    host: poc01-typesense.example.com
    ingressClassName: shared-external
  metrics:
    release: kube-prometheus-stack
  replicas: 3
  resources:
    limits:
      cpu: 1024m
      memory: 1280Mi
    requests:
      cpu: 100m
      memory: 512Mi
  storage:
    size: 3164Mi
    storageClassName: gp2
```
