### ISSUE TITLE
Allow custom directives to proxy configmap

### ISSUE THREAD

**Issue by jmiller-ca** [akyriako/typesense-operator#39]
Good Day, we have a need to add a larger max-body size to the proxy nginx nodes.

I was able to hack in temporary by updating the config map and adding in client_max_body_size 2M

```
apiVersion: v1
data:
  nginx.conf: "events {}\n\t\t\t\thttp {\n\t\t\t\t  server {\n\t\t\t\t\tlisten 80;\n\n\t\t\t\t\tclient_max_body_size 2M;\n\n\t\t\t\t\tlocation / {\n\t\t\t\t\t  proxy_pass http://c01-svc:8108/;\n\t\t\t\t\t  proxy_pass_request_headers on;\n\t\t\t\t\t}\n\t\t\t\t  }\n\t\t\t\t}"
kind: ConfigMap
metadata:
  labels:
    app: c01-rp
  name: c01-reverse-proxy-config
  namespace: qa01-typesense
  ownerReferences:
    - apiVersion: networking.k8s.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Ingress
      name: c01-reverse-proxy
```

I then rolled the proxy pods. While the operator does currently update the proxy configmap automatically it does not roll the pods so this works as a short term hack, but I am looking for a longer term solution. I had a look at https://github.com/akyriako/typesense-operator/blob/70f0950e280397a5e731790faab32e3e41176563/internal/controller/typesensecluster_ingress.go but as far as I can tell there is not currently a way to support patching the proxy configmap. 

On the same note it might be nice to just be able to use our ingress controller directly and not add in the extra proxy nodes, and send traffic directly from a ingress controller to the typesense svc, but maybe there is some benefit I am missing of having the proxy nodes?

On a side note do you have a buy me a coffee link, crypto address, some other way I could personally send a small thank you for your work on this project, I know it will not cover the time you spent but I would like to be able to send you a small thank for the time you have saved me.
